function G(a,c,e){function h(){0!=I&&(K=(new Date).getTime()-I)}function l(g){F=F|g;B.narme=F}function k(g){p.a("l2("+g+")");E=E|g;T()?(h(),I=0):0==I&&(I=(new Date).getTime());B.narm=E;p.a("l2e")}function t(g){L=L|g;B.naral=L}var p=new P,d=e&&e.dvObj||window.$dv,m=e&&e.impressionId||window.$uid,v=window.Pf||c,x=Array(v.ib),b=v.Xa/v.Xb+1,f=null,q="",u={},g=0,n=Array(v.ib),r={da:{I:null,J:null,D:null,C:null,Oe:!1},g:{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,Oe:!1},va:{Ab:null,zb:null},
Gb:0},w={},C={},A,y,z={},N={},J=null,Q=!1;this.Db=function(g){if(null==J||1==J||8==J)J=g};for(c=0;c<v.ib;c++)n[c]="b"+c;var D={};e&&d&&d.CommonData&&(D.ctx=e.kb,D.cmp=e.jb,D.btreg=e.btreg,D.btadsrv=e.Qa,D.uid=e.pb,D.brid=d.CommonData.BrowserId,D.brver=d.CommonData.BrowserVersion,D.tstype=d.CommonData.Scenario);D.jsver=a?a:null;var B={},H={},I=0,K="",M="",L=0,E=0,F=0,O=0;this.Pc=function(){return I};this.rd=function(g){O=O|g;B.vct=O};this.qd=function(g){f=g;H.strp=f;this.qd=function(){}};this.ac=function(){return(new Date).getTime()};
var U=this.ac();this.Ee=function(){return U};this.qf=function(){E=E&-3;F=F&-2;F&=-3};this.Cb=function(){k(2)};this.Bf=function(){l(8);this.qc()};this.qc=function(){k(4)};this.md=function(){t(8);this.Cb()};this.xd=function(g){t(16);B.dbg9=g};this.yd=function(){t(1)};this.zf=function(){this.Cb();l(1)};this.yf=function(){this.Cb();l(2)};this.$a=function(g,b){k(8);M=p.xe(g,b)};this.vf=function(){p.a("l1");E=E&-3;k(1);p.a("l1e")};this.pd=function(){k(16)};this.re=function(){return x};this.nd=function(f,
n){m=m||e&&e.impressionId||window.$uid;p.a("ie15");if(0<=f.j){var q=Math.floor(f.j/v.Xb);0<f.j%v.Xb?q++:0<f.j&&q++;isNaN(x[q])&&(x[q]=0);x[q]+=n;f.R&&q>=b||0==f.R&&6<=q?g+=n:(timeStampTotalBuckets=g=0,this.Db(7))}p.a("ie15e")};this.xf=function(g){var b=g.Wc;null!=g.Wc&&(w.advisonl=b);null!=g.Vc&&(w.adabvvponl=g.Vc);B.dbg8="CSS1Compat"===document.compatMode?1:0;p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(B.dbg10=document.documentMode);p.a("ff52e")};this.Za=function(g){p.a("ie14");
null!=g&&(N.adbtftopg=g)};this.wf=function(g){null!=g&&(r=g)};this.od=function(g){p.a("ie19");this.wf(g.s);this.Df();p.a("ie19e")};this.Bd=function(){null!=r.da.I&&(z.vptoscrx=Math.round(r.da.I));null!=r.da.J&&(z.vptoscry=Math.round(r.da.J));null!=r.da.D&&(z.vpwdth=Math.round(r.da.D));null!=r.da.C&&(z.vphgt=Math.round(r.da.C));null!=r.g.v&&(z.adtovpx=Math.round(r.g.v));null!=r.g.u&&(z.adtovpy=Math.round(r.g.u));null!=r.g.K&&(z.adtopgx=Math.round(r.g.K));null!=r.g.L&&(z.adtopgy=Math.round(r.g.L));
null!=r.g.G&&(z.adtoscrx=Math.round(r.g.G));null!=r.g.H&&(z.adtoscry=Math.round(r.g.H));null!=r.va.Ab&&(z.scrwdth=Math.round(r.va.Ab));null!=r.va.zb&&(z.scrhgt=Math.round(r.va.zb));z.almesind=r.Gb};this.Cd=function(){if(A&&y){var g=r.g.o,b=r.g.m;A*y<g*b&&(C.dvp_adwdth=Math.round(A),C.dvp_adhgt=Math.round(y),!Q&&(1>=A||1>=y)&&1<g&&1<b&&($dv.registerEventCall(m,{adwdth:Math.round(g),adhgt:Math.round(b)}),Q=!0),A=g,y=b)}else A=null!=r.g.o?r.g.o:null,y=null!=r.g.m?r.g.m:null;null!=A&&(C.adwdth=Math.round(A));
null!=y&&(C.adhgt=Math.round(y))};this.Df=function(){h();for(var g=0;g<x.length;g++)x[g]&&(u[n[g]]=x[g]);this.Bd();this.Cd();p.F(z,w);p.F(z,C);p.F(z,N)};this.Nc=function(){if(1E3<=g)return!0;this.Db(8);return!1};this.Be=function(g){var b={};m=m||e&&e.impressionId||window.$uid;var f=-1,n=p.ye();try{d&&d.tags[m]&&d.tags[m].getTimeDiff&&(f=d.tags[m].getTimeDiff())}catch(a){}var v=[];p.F(b,D);switch(g){case 1:q=f;p.F(b,H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=n;b.napr=M;b.ismms=q;b.isumms=f;break;case 2:p.F(b,
H);p.F(b,B);b.napt=K;p.F(b,z);b.dvp_log=n;b.napr=M;b.isnmms=f;break;case 3:b.istoms=f,b.nvr=J;case 4:case 8:p.F(b,H);p.F(b,N);p.F(b,C);b.isbxdms=f;p.F(b,u);b.nvr=J;break;case 5:p.F(b,H);p.F(b,N);p.F(b,C);p.F(b,w);b.ismms=q||f;b.isiabvms=f;b.isuiabvms=f;break;case 16:p.F(b,H);p.F(b,B);b.napt=K;b.dvp_log=n;b.napr=M;b.ishems=f;break;case 7:return v.join("");default:p.F(b,H),p.F(b,u),p.F(b,B),p.F(b,w),b.napt=K,b.dvp_log=n,b.napr=M}b.evid=g;b.ctime=this.ac();return b};this.qe=function(){p.a("ie17");for(var g=
[],b=0;b<v.ib;b++)g[b]=x[b]?x[b]:0;return g};var T=this.Hc=function(){return 2==(E&2)&&8!=(L&8)||4==(E&4)||8==(F&8)&&8==(L&8)?!1:!0};this.hf=function(g){p.a("l3");g=p.ba(g);p.a("cm3e");g&&(B.dbg5=g.w,B.dbg6=g.h);p.a("l3e")};return this}function R(a,c){var e=new P,h=a&&a.impressionId||window.$uid;this.ca=function(a,k){if(c){var t=c.Be(a);k&&e.F(t,k);var p=!1;if(4==a||8==a)p=!0;this.ld(h,t,p)}};this.ld=function(a,c,e){$dv&&$dv.registerEventCall&&a&&$dv.registerEventCall(a,c,null,!e,e)}}
function S(){this.ca=function(){};this.ld=function(){}}
function V(a,c,e,h){function l(){if(1==r){try{for(var b in g)n.removeChild(g[b]);q.document.body.removeChild(n)}catch(f){}r=!1}}function k(g){g=g||0;var b=d(0);b.Zc()?7<b.ob()?(l(),C=w=r=!1):(r=!0,w=!1):20>g?(g++,setTimeout(k,50,g)):(r=w=C=!1,l())}function t(g){$dv&&$dv.tags&&$dv.tags[h]&&$dv.tags[h].getTimeDiff&&$dv.tags[h].getTimeDiff();if(null!==g.gb)for(var b=0;b<g.gb.length;b++){var f=d(b).ob();0==b?f>A&&(A=f):f>y&&(y=f)}}function p(g){for(var b=!0,f=0;13>=f;f++)var n=d(f),b=b&(null!==n&&n.Zc());
if(!b)return null;g.Ec=0;g.oc=0;g.nc=0;g.hc=0;g.Ca=0;g.gb=Array(13);b=d(0).ob();for(f=1;13>=f;f++)if(n=5<Math.abs(d(f).ob()-b),g.gb[f]=n)switch(g.Ec++,f){case 2:case 3:case 4:case 5:g.oc++;break;case 6:case 7:case 8:case 9:g.nc++;break;case 10:case 11:case 12:case 13:g.hc++}if(13===g.Ec)return g.Ca=100,t(g),!0;b=g.gb;if(!1===b[1]){if(3<=g.hc||3<=g.nc||3<=g.oc)return t(g),null;g.Ca=0;t(g);return!1}if(!0===b[1]&&(!0===b[2]&&!0===b[3]||!0===b[2]&&!0===b[4]||!0===b[3]&&!0===b[5]||!0===b[4]&&!0===b[5])||
!0===b[1]&&4==g.nc||!0===b[1]&&4==g.hc&&1<=g.oc)return g.Ca=50,t(g),!0;if(b[2]&&b[5]&&!(b[6]&&b[10]&&b[1]&&b[13]&&b[9])||b[4]&&b[3]&&!(b[8]&&b[12]&&b[1]&&b[11]&&b[7]))return t(g),null;g.Ca=0;t(g);return!1}function d(b){b=g[b];var f=null;b&&(f=b.contentWindow);return f}function m(){for(var f=u.getBoundingClientRect(),n=f.width,q=f.height,a=n/(1+x),d=q/(1+x),v=n/x,r=q/x,w=0;13>=w;w++){var c=f.left,e=f.top;switch(w){case 0:e=c=-1E5;break;case 1:c+=(n-b)/2;e+=(q-b)/2;break;case 3:c+=n-b;break;case 4:e+=
q-b;break;case 5:c+=n-b;e+=q-b;break;case 6:c+=(n-v)/2;e+=(q-r)/2;break;case 7:c+=(n-v)/2+v;e+=(q-r)/2;break;case 8:c+=(n-v)/2;e+=(q-r)/2+r;break;case 9:c+=(n-v)/2+v;e+=(q-r)/2+r;break;case 10:c+=(n-a)/2;e+=(q-d)/2;break;case 11:c+=(n-a)/2+a;e+=(q-d)/2;break;case 12:c+=(n-a)/2;e+=(q-d)/2+d;break;case 13:c+=(n-a)/2+a,e+=(q-d)/2+d}6<=w&&(c-=b/2,e-=b/2);var m=g[w];m.style.left=c+"px";m.style.top=e+"px"}}function v(){if(null!=u&&null!=u.parentNode){w=!0;n=q.document.createElement("div");q.document.body.appendChild(n);
for(var f=0;13>=f;f++){var a=q.document.createElement("iframe");a.width=b;a.height=b;a.style.position="absolute";a.frameBorder="0";a.style.visibility="hidden";a.style.zIndex=-9999999;a.style.display="block";a.src="javascript:no=false;yes=true;("+function(){window.af={Zd:100};window.Lc=no;window.cb=0;window.Uc=0;window.bd=0;window.Sf=no;window.ob=function(){return window.bd};window.Zc=function(){return window.Lc};window.Ve=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Sb=function(){window.cb++;window.Ve(window.Sb,document)};window.Sb();setInterval(function(){10>window.cb&&window.Sb();window.bd=window.cb-window.Uc;window.Uc=window.cb},window.af.Zd);window.setTimeout(function(){window.Lc=yes},250)}.toString()+")();";n.appendChild(a);g.push(a)}m()}}var x=Math.sqrt(2),b=1,f=new P,q=null,u=null,g=[],n,r=!1,w=!1,C=f.ub(a,c,e);0==f.Va()&&(b=8);var A=0,y=0;this.Ke=function(){0==w&&(0==(this.Wa()&&(null!=u&&f.Yc(u,q)?!0:!1))?r=!1:(v(),
k()))};this.Wa=function(){return C};this.Re=function(){return r};this.sd=function(g,b){q=g;u=b;this.Ke()};this.He=function(){if(0==r)return null;var g={};return null==p(g)?null:g.Ca}}
function W(a,c,e,h,l,k,t,p){this.b=new P;this.window=a;this.c=c;this.S=e;this.M=h;this.Y=t&&t.Enums.BrowserId||window.$dv.Enums.BrowserId;this.V=t&&t.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.N=l;this.gc=k;this.fa=null;this.Tc=this.window?this.b.vb(this.window.top):this.b.vb(window.top);this.Ne=this.S!=this.V.CrossDomain&&this.b.mb("ofs")&&this.Tc;this.fa=new V(this.S,this.M,t,p);null!=this.fa&&this.fa.Wa()&&this.fa.sd(this.window,this.c);this.rb=this.wb=this.pa=null;this.Ua=!1;
var d=0;this.ha={Nd:1,Od:2,Id:4,Lb:8,Hd:16,Mb:32,Md:64};this.pc=function(a,d,b,f){if(f&&f.insertBefore&&f.firstChild&&(a=this.window.document.createElement(a))){for(var q in d)a[q]=d[q];for(q in b)a.style[q]=b[q];f.insertBefore(a,f.firstChild);return a}return null};this.oe=function(a,d,b){var f=this.window.top,q=a.width,u=a.height;0>b.left?(q=a.width-Math.abs(b.left),0>d.Aa&&(q-=Math.abs(d.Aa))):0>d.Aa&&(q=a.width-Math.abs(d.Aa)+b.left,q=q>a.width?a.width:q);var g=a.width,n=Math.min(this.b.ya(f.window).clientWidth,
f.innerWidth),c=screen.availWidth-n-d.Aa,e=0;q<g?(g=q,e=n-q,0>d.Aa&&(e-=Math.abs(d.Aa))):e=n-g-b.left;0>e?(q=g-Math.abs(e),0>c&&(q-=Math.abs(c))):0>c&&(q=g-Math.abs(c)+e,q=q>g?g:q);d=screen.availHeight-d.rf-f.outerHeight;f=Math.min(this.b.ya(f.window).clientHeight,f.innerHeight)-a.height-b.top;0>f?(u=a.height-Math.abs(f),0>d&&(u-=Math.abs(d))):0>d&&(u=a.height-Math.abs(d)+f,u=u>a.height?a.height:u);0>b.top&&(u-=Math.abs(b.top));return{Gf:q,Hf:u}};this.$b=function(a,d,b,f){var q=b.D,u=b.C,g=0;b=0;
var n={width:d.right-d.left,height:d.bottom-d.top};if(0>d.bottom||0>d.right||d.top>u||d.left>q||0>=n.width||0>=n.height)return 0;0>d.top?Math.abs(d.top)>=n.height?g=0:(g=n.height+d.top,g>u&&(g=u)):g=d.top+n.height>u?u-d.top:n.height;0>d.left?Math.abs(d.left)>=n.width?b=n.width:(b=n.width+d.left,b>q&&(b=q)):b=d.left+n.width>q?q-d.left:n.width;this.Ne&&(a=this.oe(n,a,d),b=a.Gf,g=a.Hf);return 0>=b||0>=g?0:Math.round(b*g/(n.width*n.height)*(f?n.width*n.height/((f.right-f.left)*(f.bottom-f.top)):1)*100)};
this.Zb=function(a,d){try{var b={x:a.offsetLeft,y:a.offsetTop},f;a.offsetParent?(f=this.Zb(a.offsetParent,d),b.x+=f.x,b.y+=f.y):d!=d.parent&&this.b.Nb(d,d.parent)&&(f=this.Zb(d.frameElement,d.parent),b.x+=f.x,b.y+=f.y);return b}catch(q){return{x:null,y:null}}};var m=this.b.tb();this.na=function(a){if(this.S==this.V.CrossDomain)if(this.b.ua(this.window)&&this.window.$sf.ext.geom)this.na=function(){var g=this.b.Ka(this.window),b=window.outerHeight||this.window.document.documentElement.clientHeight?
this.window.outerHeight-parseInt(g.win.h):this.N.Explorer.W,f={D:null,C:null,I:null,J:null,i:!1};f.D=parseInt(g.win.w);f.C=parseInt(g.win.h);f.I=parseInt(g.win.l);f.J=parseInt(g.win.t)+b;f.i=!0;return f};else if(this.M.X==this.Y.Firefox)this.na=function(){var g=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,b=g?0:this.window.screenX-screen.left,g=g?0:this.window.screenY-screen.top,f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Firefox.W;
f.I=b;f.J=g+this.N.Firefox.W;f.i=!0;return f};else if(this.b.kc(this.window)){var d=this;this.window.context.observeIntersection(function(g){g.forEach(function(g){d.pa=g})});this.na=function(){var g={D:null,C:null,i:!1,I:null,J:null};null!=this.pa?(g.D=this.pa.rootBounds.width,g.C=this.pa.rootBounds.height):(g.D=0,g.C=0);g.i=!0;return g}}else if(this.M.X==this.Y.IE&&10<=parseInt(this.M.ta))m&&this.yb(),this.na=function(){var g=-8==this.window.screenY&&-8==this.window.screenX,b=g?0:this.window.screenX,
g=g?0:this.window.screenY,f={D:null,C:null,I:null,J:null,i:!1};f.D=this.window.outerWidth;f.C=this.window.outerHeight-this.N.Explorer.W;f.I=b;f.J=g+this.N.Explorer.W;m?(this.Ua||this.yb(),f.i=!1):f.i=!0;return f};else if(this.M.X==this.Y.IE&&/[6-9]|[10]/.test(this.M.ta)){var b=this.pc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),f=this.pc("iframe",{name:"dv_ie9onmousemove",
src:"",width:0,height:0,je:0,We:"0",Xe:"0"},{display:"inline",position:"absolute",top:0,left:0,Ff:"none",zIndex:0,border:0},this.window.document.body),q=f.contentWindow||f.window||f.contentDocument.window||f.contentWindow.window||this.window.Kf,u=b.contentDocument||b.contentWindow.document,b=f.contentDocument||f.contentWindow.document,g="<html><head><script >window.onload = "+function(g){g&&(window.event=g);isFinite(String(window.event.clientY))&&(parent.Ra={Qb:window.event.clientY,Pb:window.event.clientX,
Ad:window.event.screenY-window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",f='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(g){g&&(window.event=g);isFinite(String(window.event.clientY))&&(parent.qa={Qb:window.event.clientY,Pb:window.event.clientX,Ga:window.event.screenY-window.event.y,Fa:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";
b.open("text/html","replace");b.write(f);b.close();u.open("text/html","replace");u.write(g);u.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.na=function(){q.runMoM();u.open("text/html","replace");u.write(g);u.close();var b=this.window.qa,f=this.window.Ra,a=screen.availWidth,d=screen.availHeight,f=f?f.Ad:this.N.Explorer.W;if(b){var c=b.Fa,e=b.Ga;b.Fa>=a&&(b.Fa-=a);b.Ga>=d&&(b.Ga-=d);var v={D:null,C:null,I:null,J:null,i:!1};
v.D=this.window.outerWidth?this.window.outerWidth-20:a-b.Fa-20;v.C=this.window.outerHeight?this.window.outerHeight-f-10:d-b.Ga-10;v.I=c;v.J=e;v.i=!0}else v={D:null,C:null,I:null,J:null,i:!1},v.D=this.window.outerWidth?this.window.outerWidth-20:a-20,v.C=this.window.outerHeight?this.window.outerHeight-f-10:d-10,v.I=null,v.J=null,v.i=!1;return v}}else this.b.tb()?(this.yb(),this.na=function(){this.Ua||this.yb();var g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-
this.N.Chrome.W;g.i=!1;return g}):this.na=this.M.X==this.Y.Chrome?function(){var g={D:null,C:null,I:null,J:null,i:!1},b=!1;try{g.D=this.window.frameElement.offsetParent.parentNode.clientWidth,g.C=this.window.frameElement.offsetParent.parentNode.clientHeight,b=!0}catch(f){}g.I=this.window.screenX;g.J=this.window.screenY;g.i=b;return g}:null!=this.fa&&this.fa.Wa()?function(){var g={D:null,C:null,I:null,J:null,i:!1};g.D=this.window.outerWidth;g.C=this.window.outerHeight-this.N.Safari.W;g.i=!1;return g}:
function(){return{D:null,C:null,I:null,J:null,i:!1}};else this.na=function(){var g,b,f=this.window.top;void 0!=f.mozInnerScreenX&&null!=f.mozInnerScreenX?(g=f.mozInnerScreenX,b=f.mozInnerScreenY):void 0!=f.screenX&&null!=f.screenX?0!=f.screenLeft+8&&f.screenLeft+8!=screen.width||0!=f.screenTop+8&&f.screenTop+8!=screen.height?(g=f.screenLeft,b=f.screenTop+(f.outerHeight-f.innerHeight)):(g=f.screenLeft+8,b=f.screenTop+(f.outerHeight-f.innerHeight)+8):(g=f.screenLeft,b=f.screenTop);var a={D:null,C:null,
I:null,J:null,i:!1},d=this.b.ya(f);a.D=f.innerWidth||d.clientWidth;a.C=f.innerHeight||d.clientHeight;a.I=g;a.J=b;a.i=!0;return a};return this.na(a)};this.ma=function(a,c){d=1;this.S==this.V.CrossDomain?this.b.ua(this.window)&&this.window.$sf.ext.geom&&this.b.Ka(this.window).par?(d=8,this.ma=function(){var b=this.b.Ka(this.window),f=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(b.win.h):this.N.Explorer.W,a={v:null,u:null,K:null,L:null,G:null,
H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};a.v=parseInt(b.self.l)-parseInt(b.par.l);a.u=parseInt(b.self.t)-parseInt(b.par.t);a.K=parseInt(b.self.l);a.L=parseInt(b.self.t);a.G=parseInt(b.win.l)+a.v;a.H=parseInt(b.win.t)+a.u+f;a.o=parseInt(b.self.w);a.m=parseInt(b.self.h);a.i=!0;a.rect={top:a.u,bottom:a.u+a.m,left:a.v,right:a.v+a.o};return a}):this.M.X==this.Y.Firefox?this.ma=function(){var b=1;window.devicePixelRatio&&(b=window.devicePixelRatio);var f=this.window.screenX,a=this.window.screenY,
d=this.window.mozInnerScreenX/b-f,b=this.window.mozInnerScreenY/b-a-this.N.Firefox.W,d={left:d,top:b,right:d+this.window.innerWidth,bottom:b+this.window.innerHeight},b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};b.v=d.left;b.u=d.top;b.K=null;b.L=null;b.G=f+d.left;b.H=a+d.top;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.i=!0;b.rect=d;this.b.Fb()&&(b=this.lb(b));return b}:this.b.kc(this.window)?(d=32,this.ma=function(){var b={v:null,u:null,o:null,
m:null,i:!1,rect:null,P:null,oa:null,K:null,L:null,G:null,H:null};null!=this.pa?(b.v=this.pa.boundingClientRect.left,b.u=this.pa.boundingClientRect.top,b.o=this.pa.boundingClientRect.width,b.m=this.pa.boundingClientRect.height):(b.v=0,b.u=0,b.o=0,b.m=0);b.i=!0;b.rect={top:b.u,bottom:b.u+b.m,left:b.v,right:b.v+b.o};return b}):this.M.X==this.Y.IE&&10<=parseInt(this.M.ta)?this.ma=function(b){var f=this.window.screenLeft-window.screenX,a=this.window.screenTop-window.screenY-this.N.Explorer.W,f={left:f,
top:a,right:f+this.window.innerWidth,bottom:a+this.window.innerHeight},a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};a.v=f.left;a.u=f.top;a.K=null;a.L=null;a.G=b.I+f.left;a.H=b.J+f.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.i=!m;a.rect=f;this.b.Fb()&&(a=this.lb(a));return a}:this.M.X==this.Y.IE&&/[6-9]|[10]/.test(this.M.ta)?this.ma=function(){if(8==document.documentMode)return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,
rect:null,P:null,oa:null};var b=this.window.Ra&&this.window.qa?this.window.Ra.Qb-this.window.qa.Qb:0,f=this.window.Ra&&this.window.qa?this.window.Ra.Pb-this.window.qa.Pb:0,a=this.b.ya(this.window),d={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};d.v=f;d.u=b;d.K=null;d.L=null;d.G=this.window.qa?f+this.window.qa.Fa:null;d.H=this.window.qa?b+this.window.qa.Ga:null;d.o=this.window.innerWidth||a.clientWidth;d.m=this.window.innerHeight||a.clientHeight;d.i=!0;d.rect=
{left:f,top:b,right:f+(this.window.innerWidth||a.clientWidth),bottom:b+(this.window.innerHeight||a.clientHeight)};this.b.Fb()&&(d=this.lb(d));return d}:this.b.tb()?(d=512,this.ma=function(){var b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};null!=this.c&&(adData=this.b.nb(this.c),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}):this.ma=this.M.X==this.Y.Chrome?function(){var b=null,f=null,a=!1;try{var d=this.window.frameElement.offsetTop,
b=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,f=d-this.window.frameElement.offsetParent.scrollTop,a=!0}catch(g){}d={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};d.v=b;d.u=f;d.K=null;d.L=null;d.G=null;d.H=null;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.i=a;d.rect=a?{left:b,top:f,right:b+this.window.innerWidth,bottom:f+this.window.innerHeight}:null;this.b.Fb()&&(d=this.lb(d));return d}:null!=this.fa&&this.fa.Wa()?
function(){var b={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null};null!=this.c&&(adData=this.b.nb(this.c),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}:function(){return{v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null}}:this.ma=function(b){var f=this.Zb(this.c,this.window),a={v:null,u:null,K:null,L:null,G:null,H:null,o:null,m:null,i:!1,rect:null,P:null,oa:null},d=this.b.bc(this.c,
this.window),g=this.b.vc(this.c,this.window);a.v=g.left;a.u=g.top;a.K=f.x;a.L=f.y;a.G=b.I+g.left;a.H=b.J+g.top;a.o=g.w;a.m=g.h;a.i=!0;a.rect=d;a.P=g;return a};return this.ma(a,c)};this.lb=function(a){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return a;var d=this.b.nb(this.c);if(d){var b=d.w,f=d.h,q=a.v,c=a.u,g=a.H,n=a.G;null!=a.v&&null!=a.u&&null!=a.m&&null!=a.o&&a.rect&&(0<d.t?(c=a.u+d.t,null!=a.H&&(g=a.H+d.t)):f+=d.t,0<d.l?(q+=d.l,null!=a.G&&(n=a.G+d.l)):
b+=d.l,d.r>a.o&&(b-=d.r-a.o),d.Dc>a.m&&(f-=d.Dc-a.m),a.o=0<b?b:0,a.m=0<f?f:0,a.v=q,a.u=c,a.H=g,a.G=n,a.rect.left=a.v,a.rect.top=a.u,a.rect.right=a.v+d.w,a.rect.bottom=a.u+d.h,a.P={w:b,h:f,left:q,right:q+b,top:c,bottom:c+f})}return a};this.De=function(){var a=screen.availWidth,d=screen.availHeight,b=screen.width,f=screen.height,c=0,e=0;this.Tc&&(e=this.window.top,c=e.screenX,e=e.screenY);return{i:this.N.Va?!1:"undefined"!==typeof c,Ab:a||b,zb:d||f,Qf:c,Rf:e,Aa:c-(b-a),rf:e-(f-d)}};this.me=function(){var a=
this.De(),d=this.na(a),b=this.ma(d,a);return{da:d,g:b,va:a,Gb:(null==d.I||null==d.J?0:this.ha.Nd)|(null==d.D||null==d.C?0:this.ha.Od)|(null==b.v||null==b.u?0:this.ha.Id)|(null==b.K||null==b.L?0:this.ha.Lb)|(null==b.G||null==b.H?0:this.ha.Hd)|(null==b.m||null==b.o?0:this.ha.Mb)|(null==a.zb||null==a.Ab?0:this.ha.Md),R:this.Ic(b.m,b.o)}};this.Ic=function(a,d){null==a&&(a=0);null==d&&(d=0);return 1!=this.N.Va?242500<=a*d:!1};this.ue=function(){this.b.a("c10");if(null!=this.c)if(this.b.Yc(this.c,this.window))try{var a=
{timeStamp:new Date,j:-3,ia:-3,s:null,R:!1,ea:0};if(!this.gc())return a;var c=this.me(),b;if(!c.g.i||!c.da.i){if(this.b.ua(this.window)&&this.window.$sf.ext.inViewPercentage)return b=this.window.$sf.ext.inViewPercentage(),{timeStamp:new Date,j:b,ia:b,s:c,R:c.R,ea:16};if(m&&this.Ua)return b=0,null!=this.rb&&(b=Math.round(100*this.rb.intersectionRatio)),{timeStamp:new Date,j:b,ia:b,s:c,R:this.Ic(c.g.m,c.g.o),ea:512};if(this.fa.Wa()){var f={timeStamp:new Date,j:-3,ia:-3,s:null,R:!1,ea:2};if(0==this.fa.Re())f.j=
-6,f.ia=-6,this.fa.sd(this.window,this.c);else{var e=this.fa.He();null!=e&&(f.s=c,f.R=c.R,f.j=e,f.ia=e)}return f}a.s=c;d&&(a.ea=d);return a}if(c.g&&c.g.P&&(0===c.g.P.w||1===c.g.P.w||0===c.g.P.h||1===c.g.P.h))return{timeStamp:new Date,j:-5,ia:-5,s:c,ea:d};b=c.g.P?this.$b(c.va,c.g.P,c.da,c.g.rect):this.$b(c.va,c.g.rect,c.da);return{timeStamp:new Date,j:b,ia:b,s:c,R:c.R,ea:d}}catch(u){return{timeStamp:new Date,j:-4,ia:-4,s:null,R:!1,ea:d}}else return{timeStamp:new Date,j:-2,ia:-2,s:null,R:!1,ea:0};else return{timeStamp:new Date,
j:-1,ia:-1,s:null,R:!1,ea:0}};this.ne=function(a,d){this.b.a("c11");var b=null,f=null;if(null!=a.s){var c=a.s.g;d<=this.N.cf&&(b=0<=a.j||-5==a.j?a.R&&a.j>=this.N.Xa||0==a.R&&50<=a.j?!0:!1:null,f=a.R?this.N.Xa/100:.5,f=0==b?0>c.u+c.m*f?!0:!1:1==b?!1:null)}return{Vc:f,Wc:b}};this.sb=function(a){this.b.a("c12");var d=null;if(2!=a.ea&&512!=a.ea&&null!=a.s){var b=a.s.Gb,f=a.s.g;(b&this.ha.Lb)==this.ha.Lb&&(b&this.ha.Mb)==this.ha.Mb&&(d=this.$b(a.s.va,{left:f.K,top:f.L,right:f.K+f.o,bottom:f.L+f.m},a.s.da,
f.rect),d=0<=a.j?a.R&&d>=this.N.Xa||0==a.R&&50<=d?!1:!0:null)}this.b.a("c12e");return d};this.yb=function(){function a(b){b.forEach(function(b){c.rb=b})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(d=512,this.wb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.wb.observe(this.c),this.Ua=!0)};this.Je=function(){this.c=null;null!=this.wb&&(this.wb.disconnect(),this.rb=null,this.Ua=!1)}}
function P(){this.getElementVolume_object=function(a){var c=a.getAttribute("width"),e=a.getAttribute("height");null==c||""==c||null==e||""==e?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:c,h:e};return a};this.Se=function(a){var c=0;try{for(;null!=a&&10>c;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;c++}}catch(e){}return!0};this.ba=function(a,c){this.a("cm1");var e=null,h=a.nodeName.toLowerCase();c&&this["getElementVolume_"+
h]&&(e=this["getElementVolume_"+h](a));if(!e&&(e=this.nb(a),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.nb=function(a){this.a("cm2");try{var c;return document.body.getBoundingClientRect&&(c=a.getBoundingClientRect())?{w:c.right-c.left,h:c.bottom-c.top,l:c.left,t:c.top,Dc:c.bottom,r:c.right}:null}catch(e){return null}};this.ya=function(a){return a.document.documentElement.clientHeight?
a.document.documentElement:a.document.body};this.Oc=function(a,c){this.a("ff9");var e=0,h=!1;if(a.document.all)for(var l=0;l<a.document.all.length;l++)"BODY"==a.document.all[l].nodeName&&(h=!0),h&&("width"==c?a.document.all[l].width>e&&(e=a.document.all[l].width):a.document.all[l].height>e&&(e=a.document.all[l].height));this.a("ff9e");return e};this.ad=function(a,c){for(var e=this.ya(a),h=a.innerWidth||e.clientWidth||this.Oc(a,"width"),e=a.innerHeight||e.clientHeight||this.Oc(a,"height"),l=c.length,
k=0,t=0;t<l;t++)if(15>=Math.abs(h-c[t].w)){k=c[t].h.length;for(h=0;h<k;h++)if(15>=Math.abs(e-c[t].h[h]))return!0;break}return!1};this.Ef=function(a){for(var c=[],e=-1;c[++e]=a[e];);c.length--;return c};this.Ib=function(a,c,e,h){var l=a.getElementsByTagName("*"),l=this.Ef(l);l.unshift(a);for(var k=["EMBED","IFRAME","OBJECT","IMG","DIV"],t=[],p=0;p<l.length;p++){var d=l[p];if(-1!=k.indexOf(d.nodeName)){var m=h(d);m&&t.push({Cc:m.w*m.h,w:m.w,h:m.h,type:d.nodeName||"other",ie:d})}}t=t.sort(function(a,
d){return d.Cc-a.Cc||k.indexOf(d.type)-k.indexOf(a.type)});(c=0<t.length&&t[0].w>c&&t[0].h>e?t[0].ie:null)&&a&&(c.qb=a.qb);return c};this.Yc=function(a,c){this.a("ff10");try{if(!a)return!1;for(c||(c=window);a!=c.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==c.document}catch(e){return!1}};this.bc=function(a,c){var e=c.parent,h={left:0,right:0,top:0,bottom:0};if(a){var l=a.getBoundingClientRect();c!=e&&this.Nb(c,e)&&(h=this.bc(c.frameElement,e));h={left:l.left+h.left,right:l.right+
h.left,top:l.top+h.top,bottom:l.bottom+h.top}}return h};this.Nb=function(a,c){var e=!1;if(a==c)e=!0;else try{a.document.domain==c.document.domain&&(e=!0)}catch(h){}return e};this.ve=function(a){if(a)try{if(a.contentDocument&&this.Xc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.vb(a.contentWindow))return a.contentWindow.document}catch(c){}return null};this.Sc=function(a){return a?a.defaultView||a.parentWindow:null};this.Me=function(a,c){return-1<c.indexOf(a)};this.pe=function(a){try{return a!=
a.top&&a.parent&&this.vb(a.parent)?a.parent:null}catch(c){return null}};this.vb=function(a){try{return a&&a.document&&this.Xc(a.document)?!0:!1}catch(c){return!1}};this.Xc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(c){return!1}};this.vc=function(a,c){var e=c.parent,h={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(h=this.bc(a,c),h.w=h.right-h.left,h.h=h.bottom-h.top,c!=e&&this.Nb(c,e)&&(e=this.vc(c.frameElement,e),e.bottom<h.bottom&&(e.bottom<h.top&&(h.top=e.bottom),
h.bottom=e.bottom),e.top>h.top&&(e.top>h.bottom&&(h.bottom=e.top),h.top=e.top),e.right<h.right&&(e.right<h.left&&(h.left=e.right),h.right=e.right),e.left>h.left&&(e.left>h.right&&(h.right=e.left),h.left=e.left),h.w=h.right-h.left,h.h=h.bottom-h.top));return h};this.Tb=function(a,c){return function(){return a.apply(c,arguments)}};this.ra=function(a){try{return a?a.length?a.length:0:0}catch(c){return 0}};this.ec=function(a){for(var c=[],e=0;e<a.length;e++)this.Se(a[e])&&c.push(a[e]);return c};this.a=
function(a){try{maxLength=3,$dv&&($dv.La=$dv.La||[],$dv.La.push(a),$dv.La.length>maxLength&&$dv.La.shift())}catch(c){}};this.ye=function(){try{return $dv&&$dv.La?$dv.La.join():""}catch(a){return""}};this.ua=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=this.Ka(a),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.ua=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.ua=function(){return!1};return!1};this.Ka=function(a){a.$sf.ext.geom&&(this.Ka="function"==typeof a.$sf.ext.geom?
function(a){return a.$sf.ext.geom()}:function(a){return a.$sf.ext.geom});return this.Ka(a)};this.F=function(a,c){if(null!=a&&null!=c)for(var e in c)c.hasOwnProperty(e)&&(a[e]=c[e])};this.kc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.tb=function(){var a=!1;if(1==this.mb("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.ub=function(a,c,e){var h=e&&e.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
c.X===h.Safari&&(null===c.ta||void 0===c.ta||!/^[3-8]/.test(c.ta)))return this.ub=function(){return!0},!0;this.ub=function(){return!1};return!1};this.mb=function(a){var c,e=this.Mc();e&&e.AVO&&(c=e.AVO[a]);return c};this.Mc=function(){var a={},c=window.$dv,e=window.$uid;c.tags&&c.tags[e]&&(a=c.tags[e]);return a};this.Fb=function(){return 1==this.mb("sam")?!0:!1};this.Ta=function(a){return a.document.hasFocus()};this.Ja=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(c,
e,h,l,k){if("undefined"==typeof l||null==l)l=window;l.addEventListener(c,e,h);k&&a.cache.push([c,e,h,l])}:window.attachEvent?a.add=function(c,e,h,l,k){if("undefined"==typeof l||null==l)l=window;l["e"+c+e]=e;l[c+e]=function(){l["e"+c+e](window.event)};l.attachEvent("on"+c,l[c+e]);k&&a.cache.push([c,e,h,l])}:a.add=function(){};window.removeEventListener?a.remove=function(a,e,h,l){if("undefined"==typeof l||null==l)l=window;l.removeEventListener(a,e,h)}:window.detachEvent?a.remove=function(a,e,h,l){if("undefined"==
typeof l||null==l)l=window;l.detachEvent("on"+a,l[a+e]);l[a+e]=null;l["e"+a+e]=null}:a.remove=function(){};a.flush=function(){for(var c=0;c<a.cache.length;c++)a.remove.apply(a,a.cache[c]);a.cache=[]}};this.getElementsByClassName=function(a,c){return a.getElementsByClassName?a.getElementsByClassName(c):a.querySelectorAll?a.querySelectorAll("."+c):[]};this.Va=function(){var a=!1;if($dv&&$dv.CommonData){var c=$dv.CommonData.detectedDeliveryType;c&&0!=c?a=2==c||3==c:(c=$dv.CommonData.deviceType)&&(a=
2==c||3==c)}return a};this.xe=function(a,c){var e=a||"",h="";if(c&&(e+=": "+(c.message||""),c.stack)){var h=c.stack||"",l=h.indexOf("at ");0>l&&(l=0);h=", Stack: "+h.slice(l,h.length)}e=e.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");h=h.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");l=null;try{l=encodeURIComponent(e+h).slice(0,500)}catch(k){try{l=encodeURIComponent(e).slice(0,500)}catch(t){l=
e.slice(0,500)}}return l}}
function X(a,c,e,h,l,k){var t=new P;this.f=h;this.window=e;this.c=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.jc=null;this.M={X:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.S=l;this.V=this.dvObj.Enums.TrafficScenario;this.ja=c;this.A=k.A;115==this.dataObj.eb&&(this.A.B.h=20,this.A.B.w=20);this.pf=function(){k.gf(this.c);this.c=k.c=null};var p=[],d=["object","embed","img","iframe"];this.dataObj.spotXmode&&(d=["object","embed",
"video","iframe"]);this.Pe=function(a){t.a("a33");a=t.ba(a);return this.Qe(a)};this.Qe=function(a){if(a){var d=a.w;a=a.h;for(var e=c.length,b=0,f=0;f<e;f++)if(15>=Math.abs(d-c[f].w))for(var b=c[f].h.length,q=0;q<b;q++)if(15>=Math.abs(a-c[f].h[q]))return!0}return!1};this.se=function(){t.a("a34");return this.te()||this.sf()};this.sf=function(){t.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),d=[],c=window.parent;t.a("ff6");try{d=c.document.getElementsByTagName("script")}catch(f){}t.a("ff6e");
for(var c=d.length,b=0;b<c;b++)if(d[b]&&d[b].id&&d[b].id.substr(7)==a)return d[b];return null};this.te=function(){t.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ud=function(a){t.a("a38");var c={node:a,xa:0};a=[];for(p=[];c||0<a.length;){try{if(1==c.xa){var e=k.lc(c.node);if(e&&!k.ka(c.node)&&k.O(c.node))return k.O(e),$dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&
$dv.eventBus.dispatchEvent(window,"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:e}),c.node=e,c}var b;a:{var f=c.node;try{if(f&&-1!=d.indexOf(f.nodeName.toLowerCase())){b=!0;break a}}catch(h){}b=!1}if(b&&this.Pe(c.node)&&!k.ka(c.node)&&k.O(c.node))return c;if(c.xa<=this.A.Ze){var q,u=c.node,g=c.xa,c=[],n=u.parentNode;n&&-1==p.indexOf(n)&&(p.push(n),c.push({node:n,xa:g+1}));if(u.hasChildNodes())for(var r=0;r<u.childNodes.length;r++)u.childNodes[r]&&-1==p.indexOf(u.childNodes[r])&&1===u.childNodes[r].nodeType&&
(p.push(u.childNodes[r]),c.push({node:u.childNodes[r],xa:g+1}));var w,l=u,A=[],y=null;l&&l.parentNode&&(y=l.parentNode.firstChild);for(;y;)1===y.nodeType&&y!==l&&A.push(y),y=y.nextElementSibling||y.nextSibling;w=A;for(r=0;r<w.length;r++)w[r]&&-1==p.indexOf(w[r])&&1===w[r].nodeType&&(p.push(w[r]),c.push({node:w[r],xa:g+1}));if(q=c)for(c=0;c<q.length;c++)a.push(q[c])}}catch(h){}c=a.shift()}return{node:null}};this.Ae=function(){t.a("a37");var a=this.se(),d=null;a&&(d=this.Ud(a));return d};this.ke=function(a){t.a("a31");
if(this.c=k.ze())return this.f.yd(),this.jc=!0,this.c;if(this.dataObj.btreg&&!0===this.jc&&1<a)return this.c;"1"!=this.dataObj.displaynon&&(a=this.Ae())&&a.node&&(this.f.xd(a.xa),this.c=a.node);return this.c};return this}
function aa(a,c,e,h,l,k){function t(b,a){for(var d=[],c=0;c<x.length;c++){var g=[],g=a(b,x[c]),n=m.ra(g);if(0!=n){var e=m.Sc(x[c]);if(null!=e)for(var h=0;h<n;h++)try{g[h].qb=e,d.push(g[h])}catch(p){}}}return d}function p(b,a){return t(b,function(b,d){m.a("ff4");var g=d.getElementsByTagName(b);m.a("ff4e");return"1"!=a?g:m.ec(g)})}var d=this,m=new P,v="Microsoft Internet Explorer"==navigator.appName;this.dataObj=a;this.window=c;this.c=e;this.S=h;this.V=l;this.dvObj=void 0===k?k={}:k;this.A={B:{h:1,
w:1},If:{h:10,w:10},Ze:10};115==this.dataObj.eb&&(this.A.B.h=20,this.A.B.w=20);this.Ce=function(b){if(b.scanOrder)return b.scanOrder;var a=[1==v?"object":"embed",1==v?"embed":"object","href","img","span","iframe","frameElement","div"];b.findclass&&1==b.findclass&&a.push("classDeclaration");b.hb&&0<b.hb.length&&a.unshift("searchCustomElementsFromTag");return a};this.searchCustomElementsFromTag=function(b){for(var a=0;a<b.hb.length&&(d.Jc(b.hb[a],b),!d.c);a++);};this.Hb=[["DCF",'"'],[";",";"],["%3B",
"%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.ce=function(){var b=d.dataObj.kb+"-"+d.dataObj.jb;a.isBrandShieldOrigin&&(b+="-bs");return b.replace(RegExp(",","g"),";")};this.rc=this.ce();this.Jc=function(b,a){if(a.btreg)for(var c=p(b,a.displaynon),e=m.ra(c),g=0;g<e;g++)if(c[g]&&d.wa(a,c[g],!0)&&!d.ka(c[g])){var n=this.lc(c[g]);if(n&&(r=m.ba(n))&&r.h>d.A.B.h&&r.w>d.A.B.w&&d.O(n)){d.c=n;d.O(c[g]);break}var r=m.ba(c[g]);if(r&&r.h>d.A.B.h&&
r.w>d.A.B.w&&d.O(c[g])){d.c=c[g];break}if((n=m.Ib(c[g],d.A.B.w,d.A.B.h,m.Tb(m.ba,m)))&&d.O(n)){d.c=n;d.O(c[g]);break}}};this.div=function(b){this.Jc("div",b)};this.span=function(b){m.a("a10");if(b.btreg)for(var a=p("span",b.displaynon),c=m.ra(a),e=0;e<c;e++)if(a[e]&&d.wa(b,a[e],!0)&&!d.ka(a[e])){var g=a[e];m.a("a20");if(g&&"1"==g.getAttribute("adunit")){d.c=a[e];break}if(g=this.lc(a[e])){var n=m.ba(g);if(n&&n.h>d.A.B.h&&n.w>d.A.B.w&&d.O(g)){d.c=g;d.O(a[e]);break}}if((g=m.Ib(a[e],d.A.B.w,d.A.B.h,m.Tb(m.ba,
m)))&&d.O(g)){d.c=g;d.O(a[e]);break}}};this.object=function(b){m.a("a11");for(var a=p("object",b.displaynon),c=m.ra(a),e=0;e<c;e++)if(a[e]&&d.wa(b,a[e])&&!d.ka(a[e])){var g=m.Ib(a[e],d.A.B.w,d.A.B.h,m.Tb(m.ba,m));if(g&&d.O(g)){d.O(a[e]);d.c=g;break}}};this.embed=function(a){m.a("a12");for(var f=p("embed",a.displaynon),c=m.ra(f),e=0;e<c;e++)if(f[e]&&d.wa(a,f[e])&&!d.ka(f[e])){var g=m.ba(f[e]);if(g&&g.h>d.A.B.h&&g.w>d.A.B.w&&d.O(f[e])){d.c=f[e];break}}};this.href=function(a){m.a("a13");for(var f=p("a",
a.displaynon),c=m.ra(f),e=0;e<c;e++)if(f[e]&&d.wa(a,f[e])&&!d.ka(f[e])){var g=f[e].getElementsByTagName("img");if(0<g.length){var n=m.ba(g[0]);if(n&&n.h>d.A.B.h&&n.w>d.A.B.w&&d.O(f[e])){d.c=g[0];break}}}};this.img=function(a){m.a("a14");for(var f=p("img",a.displaynon),c=m.ra(f),e=0;e<c;e++)if(f[e]&&d.wa(a,f[e])&&0>f[e].src.indexOf("event")&&!d.ka(f[e])){var g=m.ba(f[e]);if(g&&g.h>d.A.B.h&&g.w>d.A.B.w&&d.O(f[e])){d.c=f[e];break}}};this.classDeclaration=function(a){m.a("a9");var f="undefined"!==typeof window.document.getElementsByClassName,
c="undefined"!==typeof window.document.querySelectorAll;if(a.btreg){var e=[];if(f)e=d.getElementsByClassName(a.btreg,a.displaynon);else if(c)e=d.querySelectorAll(a.btreg,a.displaynon);else return;a=m.ra(e);for(f=0;f<a;f++)if(e[f]&&!d.ka(e[f])&&(c=m.ba(e[f]))&&c.h>d.A.B.h&&c.w>d.A.B.w&&d.O(e[f])){d.c=e[f];break}}};this.iframe=function(a){m.a("a15");for(var f=p("iframe",a.displaynon),c=m.ra(f),e=0;e<c&&!d.yc(a,f[e]);e++);};this.frameElement=function(a){try{m.a("a16"),h==l.SameDomain&&d.yc(a,window.frameElement)}catch(f){}};
this.getElementsByClassName=function(a,d){return t(a,function(a,b){m.a("ff1");var g=b.getElementsByClassName(a);m.a("ff1e");return"1"!=d?g:m.ec(g)})};this.querySelectorAll=function(a,d){return t(a,function(a,b){m.a("ff3");var g=b.querySelectorAll("."+a);m.a("ff3e");return"1"!=d?g:m.ec(g)})};this.la=function(a,f){m.a("a28");return!a||!f||5>f.length?!1:null!=(d.wc?d.wc(a,f):d.Jb(a,f))?!0:d.Ub&&"function"===typeof d.Ub?d.Ub(a,f):!1};this.wa=function(a,f,c){m.a("a22");var e=null;return a.btreg&&(d.wc=
1==a.Te?d.Ed:d.Jb,e=d.Kd(a,f,c))||!d.c&&(e=d.Ld(a,f))?!0:!1};this.Pd=function(a){m.a("a21");if(a&&!d.ka(a)){var f=m.ba(a);if(f&&f.h>d.A.B.h&&f.w>d.A.B.w&&d.O(a))return d.c=a,!0}return!1};this.yc=function(a,f){m.a("a17");return d.wa(a,f)?d.Pd(f):!1};this.ka=function(a){m.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var f=0;f<a.length;f++)if(a[f]==d.rc)return!0}return!1};this.O=function(a){m.a("a18");if(a&&0==d.ka(a))try{var f=a.getAttribute("dvvisit");f?a.setAttribute("dvvisit",
f+","+d.rc):(m.a("ff5"),f=window.document.createAttribute("dvvisit"),m.a("ff5e"),f.value=d.rc,a.setAttributeNode(f));$dv.eventBus&&window&&$dv.eventBus.dispatchEvent(window,"adLocated",{adElement:a,timeStamp:(new Date).getTime()});return!0}catch(c){}return!1};this.gf=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.Ed=function(a,f){m.a("a29");var c;try{c=(new RegExp(f)).exec(a)}catch(e){c=d.Jb(a,f)}return c};this.Jb=function(a,d){m.a("a30");var c=null;-1!==
a.indexOf(d)&&(c=a);return c};this.lc=function(a){var d=null;"celtra-ad-v3"==a.className&&a.celtra&&1==a.celtra.loaded&&(d=a.celtra.viewabilityObservee);d&&(d.qb=m.Sc(d.ownerDocument)||window);return d};var x=[];this.Kd=function(a,f,c){m.a("a23");var e;try{if(a.Gc&&f&&f.hasAttribute&&f.hasAttribute("dv-view"))return!0;(e=d.la(f.id,a.btreg))||(e=d.la(f.src,a.btreg));e||(e=d.la(f.href,a.btreg));e||(e=d.la(f.getAttribute("flashvars"),a.btreg));e||(e=d.la(f.name,a.btreg));!e&&a.findclass&&1==a.findclass&&
(e=d.la(f.getAttribute("class"),a.btreg));if(!e&&d.dataObj.Ia&&0<d.dataObj.Ia.length)for(var g=d.dataObj.Ia,n=0;n<g.length&&!(e=d.la(f.getAttribute(g[n]),a.btreg));n++);e||c||(e=d.la(f.innerHTML,a.btreg));e&&!c&&(e=d.Jd(a,f));return e}catch(r){return e}};this.Da=function(a,f){m.a("a25");if(!a)return!1;a=a.toLowerCase();for(var c=0;c<d.Hb.length;c++){var e;if(f.Bc&&(e=(d.Hb[c][0]+f.Bc).toLowerCase(),e=a.indexOf(e),-1<e)||f.fd&&(e=(d.Hb[c][0]+f.fd).toLowerCase(),e=a.indexOf(e),-1<e))return!0}return!1};
this.Ld=function(a,f){m.a("a24");var c;try{if(a.Gc&&f&&f.hasAttribute&&f.hasAttribute("dv-view"))return!0;(c=d.Da(f.id,a))||(c=d.Da(f.src,a));c||(c=d.Da(f.href,a));c||(c=d.Da(f.Nf,a));c||(c=d.Da(f.name,a));c||(c=d.Da(f.innerHTML,a));if(!c&&d.dataObj.Ia&&0<d.dataObj.Ia.length)for(var e=d.dataObj.Ia,g=0;g<e.length&&!(c=d.la(f.getAttribute(e[g]),a.btreg));g++);return c}catch(n){return c}};this.Jd=function(a,f){m.a("a26");return null==a.Qa||""==a.Qa?!1:d.la(d.Dd(f),a.Qa)};this.searchByAdSrvId_8=function(a,
d){m.a("a1");var c=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=c&&(c=c.toString(),c.replace(RegExp("-","g"),"")==d)?!0:!1};this.Ub=this["searchByAdSrvId_"+(d.dataObj?d.dataObj.eb||"":"")];this.Dd=function(a){m.a("a27");if(a.outerHTML)return a.outerHTML;for(var d=a.attributes.length,c="",e=0;e<d;e++)c=c+a.attributes[e].nodeName+"="+a.attributes[e].nodeValue+" ";return c+a.innerHTML};this.ze=function(){m.a("32");var a=[];void 0===k.tags&&(k.tags={});void 0===k.tags[$uid]&&(k.tags[$uid]={});void 0!==
k.tags[$uid].spvi&&(a.push(k.tags[$uid].spvi),-1<a[0].scanOrder.indexOf(",")&&(a[0].scanOrder=a[0].scanOrder.split(",")));d.dataObj.scanOrder=this.Ce(d.dataObj);a.push(d.dataObj);var c=d.window,h=0,p=[];try{do{p.push(c.document);for(var g=p,n=c.document.getElementsByTagName("iframe")||[],r=0;r<n.length||25>r;r++){var w=null,w=m.ve(n[r]);void 0!==w&&null!==w&&0==m.Me(w,g)&&g.push(w)}c=m.pe(c)}while(c&&10>++h)}catch(l){}x=p;for(c=0;c<a.length;c++)for(h=a[c],p=0;p<h.scanOrder.length;p++)if(void 0!=d[h.scanOrder[p]]&&
(d[h.scanOrder[p]](h),d.c))return $dv&&$dv.eventBus&&$dv.eventBus.dispatchEvent&&$dv.eventBus.dispatchEvent(window,"avsAdFound",{timeStamp:(new Date).getTime(),adDomElement:d.c}),d.c;return e};return this}
function dv_CustomClientViewAssureService(a){function c(a){return{nf:{adView:a.rq.av,Le:a.rq.ic,zc:a.rq.adc,Ye:a.rq.mla,cd:a.rq.ldav,focus:a.rq.fc,Ac:a.rq.as},mf:{ed:e(a.rp.mt),ff:e(a.rp.pt),$e:e(a.rp.mr),ef:e(a.rp.pr),eventId:a.rp.eid,Fc:a.rp.bl}}}function e(a){return"string"==typeof a?Array(a):a}this.Td=dv_InViewService;this.Td(a);this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new P;this.ab=[];a=$dv.tags[$uid].dc||a.dc||[];var h=this.b.Mc().bgm,l;for(l in a)a.hasOwnProperty(l)&&
this.ab.push(new window.Yb.de(c(a[l]),h));var k=this.Kb;this.Kb=function(a){a=k(a);for(var d=0;d<this.ab.length;d++)this.ab[d].fe(a,this.Z.interval);return a};var t=this.Oa;this.Oa=function(a,d){var c={};t(a,d);if(1==this.Vb){for(var e=0;e<this.ab.length;e++){var h=this.ab[e].bf(),b;for(b in h)h.hasOwnProperty(b)&&(c[b]=h[b])}$dv.registerEventCall($uid,c)}}}window.Yb=window.Yb||{};
window.Yb.de=function(a,c){function e(a){a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&242500<=a.s.g.o*a.s.g.m&&(k=!0,h.cd&&(h.adView=h.cd),e=function(){})}var h=a.nf,l=a.mf,k=!1;this.fe=function(a,c){e(a);var l=!0,k;k=h.focus?a.j:a.ia;h.adView&&h.adView>k&&(l=!1);h.Ac&&a.s&&a.s.g&&a.s.g.m&&a.s.g.o&&a.s.g.o*a.s.g.m<h.Ac&&(l=!1);l?t+=c:h.Le&&(t=0);this.Yd(a)};var t=0;this.bf=function(){return this.jf(l.ed,l.$e,l.Fc)};this.jd=function(){this.kf(l.ed,l.ff,l.ef,l.Fc,l.eventId);this.jd=function(){}};this.Yd=function(a){(h.zc&&
t>=h.zc||k&&h.Ye)&&this.jd(a)};var p;this.jf=function(a,e,h){var l={};if(c&&h)return l;if(a)for(p=$dv.tags[$uid].getTimeDiff(),h=0;h<a.length;h++)l[a[h]]=p;if(e)for(h=0;h<e.length;h++)$dv.pubSub.publish(e[h],$uid),window&&$dv.pubSub.publish(e[h],window.$frmId);return l};this.kf=function(a,e,h,l,b){if(!c||!l){if(e){l={};for(var f=$dv.tags[$uid].getTimeDiff(),k=0;k<e.length;k++)l[e[k]]=f;b&&(l.evid=b);if(a)for(k=0;k<a.length;k++)l[a[k]]=p||$dv.tags[$uid].getTimeDiff();$dv.registerEventCall($uid,l)}if(h)for(k=
0;k<h.length;k++)$dv.pubSub.publish(h[k],$uid),window&&$dv.pubSub.publish(h[k],window.$frmId)}}};
function dv_InViewService(a){function c(){null===k.interval&&(k.interval=setInterval(k.we(),k.Z.interval))}function e(){if(!1===k.$c){k.$c=!0;try{k.b.Ja.remove("load",arguments.callee,!1,element)}catch(a){}k.Bb();k.b.a("s41");k.sa=new W(k.Xd?k.Xd:k.window,k.c,k.S,k.M,k.N,k.f.Hc,k.dvObj,k.impressionId);k.b.a("s42");k.Gd();k.start()}}function h(a,b){return a.isReportingDisabled?new S:new R(a,b)}function l(a,b){k.b.Ja.add("click",function(){k.Ob(!0);$dv.registerEventCall(k.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});k.b.Ja.remove("click",arguments.callee,!1,a)},!1,a,!1)}var k=this;this.dd=10;this.Sd=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"679";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new P;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,d,c=0;c<b;c++)if(d=a[c].src,/visit[.]js/.test(d))return d.substring(d.indexOf("?")+1)};var t=this.$c=!1,p=!1;this.Fe=function(){var a=
"";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Rc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.U=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var d=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return d=d?d[1]:null};this.Ge=function(){var a=this.U("uid",this.aa);null==
a?(a=this.Rc(),this.aa=this.aa+"&uid="+a):""==a&&(a=this.Rc(),this.aa=this.aa.replace("&uid=","&uid="+a));return a};this.pc=function(a,b,d,c){if(c&&c.insertBefore&&c.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in d)a.style[e]=d[e];c.insertBefore(a,c.firstChild);return a}return null};this.Wd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};
this.S=this.dvObj.CommonData.Scenario||this.Wd();this.M={X:this.dvObj.CommonData.BrowserId,ta:this.dvObj.CommonData.BrowserVersion};this.Y=this.dvObj.Enums.BrowserId;this.V=this.dvObj.Enums.TrafficScenario;this.Ya="default";this.dataObj=a;this.window=a.tagWindow||parent.window||window;this.c=null;this.tc=this.Pa=!1;this.mc=!0;this.interval=null;this.aa=this.Ie();this.Ba=this.Fe();a.serverSettings&&a.serverSettings.protocol&&a.serverSettings.protocol.indexOf("http");this.Z=window.he||this.window.he||
{interval:100,za:{"default":{time:null,Ja:["beforeunload","unload"],td:9E5}}};this.hd={};var d=null;this.T=window.ge||this.window.ge||{interval:1E3,$:6};var m=a&&a.vd?a.vd:!1;a=a&&a.wd?a.wd:!1;!1!==m&&!1!==a&&(this.T.interval=m,this.T.$=a,$dv.registerEventCall(this.impressionId,{Lf:this.T.interval,Mf:this.T.$}));m=this.b.Va();this.ae={ib:12,Xb:10,Xa:30};this.N={Firefox:{W:115},Chrome:{W:89},Safari:{W:38},Explorer:{W:55},cf:500,Va:m,Xa:30};var v=!1,x=0,b=[5,10,15];window.devicePixelRatio&&(this.N.Firefox.W=
0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.ja=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050,413,50,31]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800,20]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},
{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360,600]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50,100,480,320]},{w:1280,h:[100]},{w:640,h:[480,90,360]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446,90]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,
200,30]},{w:930,h:[180,600]},{w:980,h:[90,120]},{w:900,h:[240]},{w:275,h:[300]},{w:600,h:[400]},{w:168,h:[28]},{w:216,h:[36]},{w:292,h:[30]}];this.dataObj.spotXmode&&(this.ja.push({w:320,h:[240]}),this.ja.push({w:400,h:[300]}),this.ja.push({w:450,h:[338]}),this.ja.push({w:600,h:[800]}),this.ja.push({w:640,h:[360]}),this.ja.push({w:854,h:[480]}),this.ja.push({w:500,h:[375]}));this.pb=this.Ge();this.Wb=!1;this.Na=function(a,b){this.window.Kc||(this.window.Kc=[]);this.window.Kc.push({caller:a,Of:b})};
this.startTime=(new Date).getTime();this.Qd=4;this.xc=0;this.gc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Jf:17,interval:32};this.Vb=!1;this.ud=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.f.qe();this.window.dv_logObject[this.pb]=a}this.b.a("ie16e")};this.Eb=function(a){this.b.a("ie17");this.Eb=this.Wb?function(a){this.f.od(a);this.ud()}:function(a){this.f.od(a)};this.Eb(a)};this.sc=
function(a,b){this.sc=this.Wb?function(a,g){this.f.nd(a,g);this.ud()}:function(a,g){this.f.nd(a,g)};this.sc(a,b)};this.Bb=function(){this.b.a("s4");this.c=this.Rb.ke(this.T.$);!this.c&&this.S==this.V.CrossDomain&&this.b.ua(this.window)&&(this.T.$=0);if(this.c)this.tf(),this.f.hf(this.c),t||(l(this.c,"ad"),t=!0),p||this.S!=this.V.CrossDomain&&this.S!=this.V.SameDomain||(l(window.parent,"ifr"),p=!0),setTimeout(c,this.Rb.jc?10:50);else if(0<this.T.$)this.T.$--,this.uf(),setTimeout(this.le(),this.T.interval);
else{try{this.S==this.V.CrossDomain&&(this.b.ad(this.window,this.ja)||this.b.ua(this.window))?(this.c=this.b.ya(this.window),this.f.md()):this.S==this.V.SameDomain&&this.b.ad(this.window,this.ja)?(this.c=this.b.ya(window.parent),this.f.md(),this.$d()):this.T.$=-1}catch(a){this.T.$=-1}setTimeout(c,10)}this.b.a("s4e")};this.$d=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),d=b.length,c=0;c<d;c++)b[c].contentWindow==
a&&(this.c=b[c],this.window=a.parent);this.b.a("ff26e")};this.uf=function(){this.dataObj.btreg&&this.dataObj.Qa?this.f.yf():this.f.zf()};this.tf=function(){this.b.a("s9");this.Pa=!0;this.f.vf();this.b.a("s9e")};this.Rd=function(){this.dataObj.eb=this.U("adsrv",this.aa)||"";this.dataObj.btreg=this.U("btreg",this.aa)||"";this.dataObj.fd=this.U("plcid",this.aa)||"";"8"==this.dataObj.eb&&""==this.dataObj.btreg&&(this.dataObj.btreg=this.dataObj.plcid);this.dataObj.Qa=this.U("btadsrv",this.aa)||"";this.dataObj.Bc=
this.U("adid",this.aa)||"";this.dataObj.pb=this.pb;this.dataObj.Te=this.U("isbtregex",this.Ba)||"";this.dataObj.kb=this.U("ctx",this.aa)||"";this.dataObj.jb=this.U("cmp",this.aa)||"";this.dataObj.Ue=this.U("lomd",this.Ba)||"";this.dataObj.findclass=this.U("findclass",this.Ba)||"";this.dataObj.displaynon=this.U("displaynon",this.Ba)||"";this.dataObj.Gc=this.U("bsdvview",this.Ba)||"";var a=this.U("bttag",this.Ba)||"";this.dataObj.hb=0<a.length?a.split("|"):[];a=this.U("btattb",this.Ba)||"";this.dataObj.Ia=
0<a.length?a.split("|"):[]};this.gd=function(a){a=this.xb(a);return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.xb=function(a){if(!this.dvObj)return[];for(var b=[],d=0;d<a.length;d++){var c=this.dvObj.pubSub.publish(a[d],this.impressionId)||null;null!=c&&b.push(c);window&&(c=this.dvObj.pubSub.publish(a[d],window.$frmId)||null,null!=c&&b.push(c))}return b};this.zd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.aa+="&TKH="+this.dataObj.serverSettings.TKH)};this.ee=
function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),d=b.length>>>0;if(0===d)return-1;var c=0;1<arguments.length&&(c=Number(arguments[1]),c!=c?c=0:0!=c&&Infinity!=c&&-Infinity!=c&&(c=(0<c||-1)*Math.floor(Math.abs(c))));if(c>=d)return-1;for(c=0<=c?c:Math.max(d-Math.abs(c),0);c<d;c++)if(c in b&&b[c]===a)return c;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.ee();this.zd();this.Rd();this.f=new G(this.Sd,this.ae,this.dataObj);
this.ga=h(this.dataObj,this.f);this.dataObj.isRTNsDisabled&&(this.xb=function(){return[]});this.Wb=this.window.dv_logObject?!0:!1;this.Af();this.Vd=new aa(this.dataObj,this.window,this.c,this.S,this.V,this.dvObj);this.Rb=new X(this.dataObj,this.ja,this.window,this.f,this.S,this.Vd);var a=window.parent;"589953"==this.dataObj.kb&&"587351"==this.dataObj.jb||"589953"==this.dataObj.kb&&"616389"==this.dataObj.jb||"polite"==this.dataObj.Ue?(setTimeout(e,15E3),this.b.Ja.add("load",function(){setTimeout(e,
1E3)},!1,a,!1)):e()}catch(b){var c=this;this.Ea(function(){c.Na("inViewManager",b);c.f.$a("inViewManager",b);c.ga.ca(c.logEvents.errorlevel1)},"inViewManager",b)}};this.bb=function(a){this.b.a("ie20");-6!=a.j&&(-3==a.j||-5!=a.j&&0>a.j&&-1==this.T.$)&&(this.uc(),this.bb=function(){})};this.uc=function(){this.ga.ca(this.logEvents.nonMeasurable);this.xb(["IABNotMeasuredImpression"]);this.uc=function(){}};this.Oa=function(a,b){a.b.a("ie21");if(0<=b.j||-5==b.j&&-1>=a.T.$){if(a.dvObj&&a.impressionId){a.b.a("ie23");
var c=a.gd(["IABMeasuredImpression"]);a.b.a("ie24");a.ga.ca(a.logEvents.startMeasure,c)}else a.ga.ca(a.logEvents.startMeasure);a.Vb=!0;a.Oa=function(){};a.bb=function(){}}a.b.a("ie22")};this.Ob=function(a){this.b.a("ie25");if(this.f.Nc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.gd(["IABViewableImpression"]),this.b.a("ie29"),this.ga.ca(this.logEvents.iabViewable,a)):this.ga.ca(this.logEvents.iabViewable),v=!0,this.Ob=function(){};this.b.a("ie26")};this.be=
function(a){if(v&&this.f.Nc())for(x+=a,a=0;a<b.length;a++)null!=b[a]&&x>=1E3*b[a]&&(this.xb(["IABAdViewable"+b[a]+"Seconds"]),b[a]=null);else x=0};var f="hidden",q=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(var a in vis)if(vis[a]in document){f=vis[a];break}a=1==this.b.mb("fcs");var b=!1;try{this.b.Ta(this.window),b=!0}catch(c){}var d=!1;try{this.b.Ta(this.window.top),d=!0}catch(c){}var e=null,e=a&&b&&this.M.X==this.Y.IE?function(){var a=k.b.Ta(k.window);
k.S==k.V.OnPage&&(a=a&&k.mc);return a}:a&&d?function(){var a=!0,a=k.b.Ta(k.window.top);k.S==k.V.OnPage&&(a=a&&k.mc);return a}:"undefined"!==typeof document[f]?function(){return!k.window.document[f]}:d?function(){return k.b.Ta(k.window.top)}:function(){return!0};this.hasFocus=function(){try{return e()}catch(a){q++,5<=q&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.cc=function(a){var b=a.sa.ue();a.b.a("ie12");0>b.j&&this.f.Db(Math.abs(b.j));null==this.c||-3==b.j||a.hasFocus()||
(b.j=0,this.f.Db(9));a.b.a("ie13");return d=b};var u;this.Kb=function(a){var b;try{$uid&&dvObj&&dvObj.tags[$uid]&&dvObj.tags[$uid].getTimeDiff&&(b=dvObj.tags[$uid].getTimeDiff())}catch(c){}a.Z.interval=b-u||100;u=b;a.b.a("ie1");b=a.c?a.c.qb||a.window:a.window;a.sa.c=a.c;a.sa.window=b;a.b.a("ie2");b=a.cc(a);a.Pa&&(-1==b.j||-2==b.j)&&-1<=a.T.$&&(a.kd(a),a.Bb());a.b.a("ie3");-5==b.j&&(a.T.$--,a.f.pd(),a.Ma||(a.Ma=function(b){b=a.sa.sb(b);a.f.Za(b)}));a.b.a("ie4");a.Ma&&0<b.j&&(a.Ma(b),a.Ma=null);a.b.a("ie5");
if(a.Pa&&!a.tc){a.tc=!0;var d=a.sa.sb(b);a.f.Za(d)}-5==b.j&&-1<=a.T.$&&(a.kd(a),a.Bb(),b=a.cc(a),-5==b.j&&0<a.T.$&&a.f.qf());a.b.a("ie6");a.sc(b,a.Z.interval);a.b.a("ie7");a.Eb(b);a.b.a("ie8");a.f.rd(b.ea);a.bb(b);a.b.a("ie9");a.Oa(a,b);a.b.a("ie10");a.Ob();a.b.a("ie11");a.be(a.Z.interval);a.b.a("ie12");return b};this.kd=function(a){a.Pa=!1;a.c=null;a.Rb.pf();a.sa.Je()};this.we=function(){this.b.a("s26");var a=this;return function(){try{a.Kb(a)}catch(b){a.Ea(function(){a.xc<a.Qd&&(a.xc++,a.Na("getIntervalCallback",
b),a.f.$a("getIntervalCallback",b),a.ga.ca(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Qc=function(a){var b=this;return function(){b.Ea(function(){b.ga.ca(b.logEvents[a])},"getReportEventCallback")}};this.le=function(){var a=this;return function(){a.Ea(function(){a.Bb();a.c||a.f.Cb()},"getAdLocateCallback")}};this.Sa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.mc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ea(function(){a.Na("getFocBluEventCallback",
c);a.f.$a("getFocBluEventCallback",c);a.ga.ca(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.f.re().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*
c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.Vb,totalPageTime:(a.f.ac()-a.f.Ee())/1E3,notApplicableTime:a.f.Pc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Gd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=d.j;0<=d.j&&d.s&&d.s.g&&(a.adWidth=d.s.g.o,a.adHeight=d.s.g.m);return a};a.VA.getAdElem=function(){return k.c}}}catch(b){}};this.Fd();this.start=
function(){this.b.a("s35");this.df(this);var a;this.Z&&this.Z.za&&this.Z.za[this.Ya]&&(a=this.Z.za[this.Ya].Ja);if(a)for(var b=a.length,c=0;c<b;c++)this.hd[a[c]]=this.Qc(a[c]),this.Ha(this.window,a[c],this.hd[a[c]]);this.Cf();this.Z&&this.Z.za&&this.Z.za[this.Ya]&&this.Z.za[this.Ya].td&&setTimeout(this.lf(),this.Z.za[this.Ya].td)};this.lf=function(){var a=this;return function(){a.Qc("timeout")();clearInterval(a.interval);a.ga.ca=function(){}}};this.df=function(a){try{var b=a.cc(a);-5==b.j&&(this.f.pd(),
this.Ma||(this.Ma=function(b){b=a.sa.sb(b);a.f.Za(b)}));if(a.Pa)if(this.tc=!0,-5!=b.j){var c=a.sa.sb(b);a.f.Za(c)}else a.f.Za("true");a.f.rd(b.ea);var d=a.sa.ne(b,a.f.Pc());a.f.xf(d);a.f.qd(b.j);a.Eb(b);a.bb(b);a.Oa(a,b)}catch(e){a.Ea(function(){a.Na("onStartReport",e);a.f.$a("onStartReport",e);a.ga.ca(a.logEvents.errorlevel1)},"onStartReport",e)}};this.Cf=function(){this.Ha(this.window,"blur",this.Sa());this.Ha(this.window,"focus",this.Sa());this.Ha(this.window.document,"click",this.Sa());this.Ha(this.window.document,
"mousedown",this.Sa());this.Ha(this.window.document,"mouseup",this.Sa())};this.Ha=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Af=function(){this.b.a("ff24");this.S==this.V.CrossDomain?this.b.ua(this.window)||this.b.kc(this.window)||this.b.tb()||this.b.ub(this.S,this.M,this.dvObj)||(this.M.X!=this.Y.Firefox&&
this.M.X!=this.Y.IE?this.f.Bf():this.M.X==this.Y.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.f.qc()):window.document.body.getBoundingClientRect||this.f.qc();this.gc=this.f.Hc();this.b.a("ff24e")};this.Ea=function(a,b,c){try{a()}catch(d){try{0<this.dd&&(this.dd--,a=c||d,b=b||"unknown caller",this.Na(b,a),this.f.$a(b,a),this.ga.ca(k.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){(new dv_CustomClientViewAssureService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs679");
if(tagObject){var serviceParams=tagObject.services.avs679;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
